sonar.projectKey=projeto-final-devops
sonar.sources=user-service,product-service
sonar.exclusions=tests/**,**/tests/**,**/test_*.py,**/products_tests/**,**/venv/**,**/__pycache__/**
sonar.python.version=3.11
