apiVersion: v1
kind: Namespace
metadata:
  name: monitoring
  labels:
    name: monitoring
    project: projeto-final # Label identifies the project to which the monitoring namespace belongs
    phase: monitoring